# Generated by Django 5.1.1 on 2024-10-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abasomyi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='umusomyi',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
